services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      # Mount volume untuk menyimpan hasil build
      - ./.next:/app/.next
      - ./prisma:/app/prisma
      - prisma_generated:/app/prisma/generated  # Named volume untuk Prisma generated
      - ./node_modules/.prisma:/app/node_modules/.prisma
    env_file:
      - .env.build
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=4096 --no-experimental-fetch --experimental-global-webcrypto

volumes:
  prisma_generated: # Volume untuk menyimpan hasil Prisma generate
  build_node_modules: 