services:
  app:
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules  # Named volume untuk node_modules   
      - prisma_generated:/app/prisma/generated  # Volume untuk menyimpan hasil generate Prisma
    env_file:
      - .env
      - .env.local
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max_old_space_size=4096
    command: yarn dev
    restart: unless-stopped

  test:
    build:
      context: .
      target: test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - prisma_generated:/app/prisma/generated  # Volume untuk menyimpan hasil generate Prisma
    env_file:
      - .env
      - .env.local
    environment:
      - NODE_ENV=test
      - NODE_OPTIONS=--max_old_space_size=4096
      - USE_BABEL=true
    command: yarn test

volumes:
  node_modules:
  prisma_generated:  # Volume baru untuk menyimpan hasil generate Prisma
